name: CI Pipeline - BTC Volatility API

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar repositorio
      - uses: actions/checkout@v3

      # 2. Configurar Python 3.10
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # 3. Instalar dependencias
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8

      # 4. Ejecutar linter
      - name: Run Linter
        run: flake8 app/ --ignore=E501,W503

      # 5. Ejecutar tests unitarios
      - name: Run Tests
        run: pytest tests/ -v


